site_name: Saiblo Wiki
nav:
- 首页: index.md
- 用户手册: user/user.md
- AI 编写手册:
  - AI 编写手册: ai/ai.md
  - 基于 CLion 的 C++ 环境配置: ai/cpp-env-clion.md
  - 基于 VS Code 的 C++ 环境配置: ai/cpp-env-vscode.md
- 游戏开发者手册: developer/developer.md
- 游戏手册:
    - 黑白棋: games/reversi.md
    - 四子棋:
        - 游戏介绍: games/connect4/connect4.md
        - 实验框架介绍: games/connect4/sdk.md
        - 在线平台介绍: games/connect4/saiblo-guide.md
        - 本地评测工具介绍: games/connect4/local-guide.md
        - 作业提交与评分细则: games/connect4/submission.md
    - 神迹之战:
        - 游戏介绍: games/miracle/miracle.md
        - 通讯协议: games/miracle/communicate.md
        - SDK 文档: games/miracle/sdk.md
        - 游戏逻辑文档: games/miracle/logic.md
    - 鱼洋陷役:
        - 快速入门: games/aquawar/aquawar.md
        - 游戏规则: games/aquawar/rules.md
        - SDK手册: games/aquawar/sdk.md
        - 通讯协议: games/aquawar/communication.md
    - 抢金蛋: games/eggs.md
    - 失落深空:
        - 游戏简介: games/lostspace/lostspace.md
        - 游戏规则: games/lostspace/rules.md
        - 通讯协议: games/lostspace/communication.md
        - C++ AI 快速上手文档: games/lostspace/cpp-quick-start.md
        - Python AI 快速上手文档: games/lostspace/py-quick-start.md
        - C++ AI SDK 文档: games/lostspace/cpp-sdk.md
        - Python AI SDK 文档: games/lostspace/py-sdk.md
        - 回放文件格式说明: games/lostspace/replay.md
    - 日本麻将:
        - 游戏引导: games/mahjong/mahjong.md
        - 游戏规则: games/mahjong/rules.md
        - SDK 文档: games/mahjong/sdk.md
        - 播放器使用说明: games/mahjong/player.md
    - 贪吃蛇围棋:
        - 详细规则及边界情况: games/snake-go/snake-go.md
        - Python ADK 用户说明 (Lite): games/snake-go/adk-lite.md
        - Python ADK 用户说明 (Advanced): games/snake-go/adk-advanced.md
        - C++ ADK 用户说明: games/snake-go/cpp-guide.md
        - 常见问题解答: games/snake-go/faq.md
        - 通讯协议: games/snake-go/ai-protocol.md
        - 回放文件格式简介: games/snake-go/replay-guide.md
    - 冰雪杯:
        - 游戏简介: games/snow-cup/snow-cup.pdf
        - C++ SDK 手册: games/snow-cup/cpp-intro.pdf
        - Python SDK 手册: games/snow-cup/py-intro.pdf
use_directory_urls: false

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: material

# To run locally:
#     pip install mkdocs
#     pip install mkdocs-material
#     mkdocs serve
