site_name: Saiblo Wiki
nav:
- 首页: index.md
- 用户手册: user/user.md
- AI 编写手册: ai/ai.md
- 游戏开发者手册: developer/developer.md
- 游戏手册:
    - 黑白棋: games/reversi.md
    - 鱼洋陷役:
        - 快速入门: games/aquawar/aquawar.md
        - 游戏规则: games/aquawar/rules.md
        - SDK手册: games/aquawar/sdk.md
        - 通讯协议: games/aquawar/communication.md
    - 贪吃蛇围棋:
        - 游戏说明: games/snake-go/snake-go.md
        - AI 编写说明 (Lite): games/snake-go/adk-lite.md
        - AI 编写说明 (Advanced): games/snake-go/adk-advanced.md
use_directory_urls: false

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme:
    name: material

# To run locally:
#     pip install mkdocs
#     pip install mkdocs-material
#     mkdocs serve
