site_name: Saiblo Wiki
nav:
- 首页: index.md
- 用户手册: user.md
- 游戏开发者手册: developer/developer.md
- 游戏手册:
    - 黑白棋: games/reversi.md
use_directory_urls: false

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true

extra_javascript:
    - config.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

theme: readthedocs
